### ISSUE TITLE
usage question for grounded theory

### ISSUE THREAD

**Issue by robinsonkwame** [ryanjamurphy/obsidian-qualitative-analysis-environment#1]
Love this project! I have a couple of questions:

a) Can you provide a quick example of using this to go from initial coding to axial and selected coding in a way that does not remove prior coding?
b) Is there a way of assigning codes to snippets of text (e.g. like a hyperlink). This would reduce the need to reduce  the text while losing some surrounding context.

**Comment by ryanjamurphy** [comment]
> a) Can you provide a quick example of using this to go from initial coding to axial and selected coding in a way that does not remove prior coding?

hmm. When I used this approach, I coded the codes — because each code is its own note, this allows you to add layers. Does that make sense? (You might be using a more specific coding process than I was!)

> b) Is there a way of assigning codes to snippets of text (e.g. like a hyperlink). This would reduce the need to reduce the text while losing some surrounding context.

Great question because I think there are many answers. You can decompose and recompose notes (e.g., extract a chunk of text in a note into a new note, and embed it in the original source). There are also a variety of plugin approaches that could work... E.g., create a Dataview `::` metadata field for each code and assign the chunk of text to the field. (e.g., `patient-loneliness:: "Some quote from an interviewee."`) Then, you'd create dataview queries to grab all of these results. I haven't given much thought to these alternatives, though.
